# Generated by Django 4.2 on 2025-07-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='prices',
            new_name='show_lower_button',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='show_prices',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='show_sizes',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='show_upper_button',
            field=models.BooleanField(null=True),
        ),
    ]
