# Generated by Django 4.2 on 2025-07-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_rename_prices_apiuser_show_lower_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='title_for_lower_button',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='title_for_upper_button',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='url_for_lower_button',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='url_for_upper_button',
            field=models.URLField(blank=True, null=True),
        ),
    ]
