# Generated by Django 4.2 on 2025-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='url_for_search',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
