# Generated by Django 4.2 on 2025-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_apiuser_url_for_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='url_for_search',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
