# Generated by Django 4.2 on 2025-07-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_apiuser_url_for_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='specification',
            field=models.CharField(choices=[('Paminklai', 'Paminklai'), ('Sonai', 'Sonai'), ('Takai', 'Takai'), ('Plokstes', 'Plokstes'), ('Priedai', 'Priedai')], max_length=10),
        ),
    ]
