# Generated by Django 4.2 on 2025-08-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_item_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='show_lower_lower_button',
            field=models.BooleanField(null=True),
        ),
    ]
