# Generated by Django 4.2 on 2025-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_apiuser_show_lower_lower_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='show_logo_on_main_page',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='show_logo_on_preview',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='title_for_lower_lower_button',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='url_for_lower_lower_button',
            field=models.URLField(blank=True, null=True),
        ),
    ]
